apiVersion: v2
name: telemetry-manager
description: Kyma Telemetry Manager Helm Chart
version: 2.0.0
type: application
appVersion: "2.0.0"
keywords:
  - kyma
  - telemetry
  - observability
  - monitoring
  - logging
  - tracing
  - opentelemetry
maintainers:
  - name: kyma-project.io
    url: https://kyma-project.io
dependencies:
  - name: experimental
    version: 2.0.0
    condition: experimental.enabled
  - name: regular
    version: 2.0.0
    condition: regular.enabled
